---

name: Push Helm Chart to ChartMuseum
on: 
  push:
    paths:
      - 'charts/**'
      - '!charts/*-*-values.yaml'
    branches:
      - main

jobs:
  push_helm_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo 
        uses: actions/checkout@v3

      - name: Install Helm 
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Install Helm ChartMuseum plugin
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push
      
      - name: Add ChartMuseum repo 
        run: |
          helm repo add uclalibcm https://chartmuseum.library.ucla.edu
      
      - name: Push Helm Chart to ChartMuseum repo
        env: 
          HELM_REPO_USERNAME: ${{ secrets.CM_BASICAUTH_USERNAME }}
          HELM_REPO_PASSWORD: ${{ secrets.CM_BASICAUTH_PASSWORD }}
        run: |
          helm cm-push charts/ uclalibcm
